sprite $Application_Module [48x45/16z] {
vTK5ZWCn343Hn7QOxd_RLRnAf26N-OchttOcgARGpl7KldY9I-i-AIrGRjDhKU_r55lBYAWdGBRiwzJ-eHv2OsRHRz3T--I6S5Rlr1WmStxFpki33gxtSo1Z
OmwPyBxt_BnEv_KmnTQAjHQ4_c1zdjzhveKUfxu-YVhmszBbkkpFN3_FxwCPlDIVjpxFxzLH7sZrF6WwIkU-ht_X-boULsG8bkz5b4-kj-MufRDx_ICz40FD
a9W-w0NkrlkhM55ywdtjopd-
}

