sprite $Application_System [48x44/16z] {
lPC7iiCW34G52E42xFrFcyxE12ROlxvKY-SchuJiECE_-ZbEMNj_TpCa3Rwu6NS_a0mKC_DSLhCu-0FAvGsentxWyWgKh_ZR1t_n3QFlIwsuKMkDlPzOYA0F
ClWchS5AtrNwAfsVryR-zFNs5y2UqkDdNTFyVfTsNl5ua2U-ifx4XS4lf3wtWdDs-m6mXc00QYahVGXPcRUnFx_XBwVyZHIWvfnV_TUeEr1Zr2tdzKm-vPMt
FEzdwFBCEQAVjqP-y-rMCRFocYFwQSWF2I0wpUVe1_gByq-SlVlUAuZwbYlKHZUFpufvRqy91_tXyuhuZFQ-YYY8aXqeAILFNpalEu0rfNt8Zr0UOkITs9ZF
3XtwF_T3AHatSYdXm2Sxwt_WCy_d_Q0Q9lw4qPUPBeDVqfIjyu_vU_yA
}

