sprite $Application_Module [48x44/16z] {
xTK53WCX48NXuiwx_sahJ5XViXxh7ntuuiYhos5BZ_faceMf3woPEU15Lm2Yaf9tsqAM-CXFoxBRTYYffiVCwxFUgPhTv4steAxmQkgzDfHsv0LD4IMdoyIh
doIlNOzT6K3EgUMdvoSA8TWstvstYxtjIa1opWh6P9bDdFXjv-Uypx6MDddBQtgJdvwtxLvlyYdK4gqhclB4Ft8-JLS4ilTUT3xvKjvwVWnDOUB_NjgIf4dJ
n1Tzg_C-obR2JJsGMptnNty
}

