!$PUML_THEME = "archimate-lowsaturation"
!$THEME      = "archimate-lowsaturation"

!$STRATEGY_FILLCOLOR = "#f9c268"
!$BUSINESS_FILLCOLOR = "#fcea83"
!$APPLICATION_FILLCOLOR = "#bfd9f0"
!$TECHNOLOGY_FILLCOLOR = "#cfde7a"
!$PHYSICAL_FILLCOLOR = "#PHYSICAL"
!$MOTIVATION_FILLCOLOR = "#cab5ea"
!$IMPLEMENTATION_FILLCOLOR = "#f18b8b"
!$OTHER_FILLCOLOR = "#dfaacb"
!$JUNCTIONOR_FILLCOLOR = "#WhiteSmoke"
!$JUNCTIONAND_FILLCOLOR = "#Black"
!$GROUP_FILLCOLOR = "#ffc73f"
!$FOLDER_LINECOLOR = "#4f4f4f"
!$RELATIONSHIP_LINECOLOR = "#Black"
!$RELATIONSHIP_FONTCOLOR = "#Black"
!$RELATIONSHIP_FONTSIZE = 10

!$TITLE_FONTSIZE = 14
!$DEFAULT_FONT = "Verdana"
!$DEFAULT_FONTSIZE = 12

skinparam defaultFontName       $DEFAULT_FONT
skinparam defaultFontSize       $DEFAULT_FONTSIZE
skinparam defaultTextAlignment  center
skinparam wrapWidth             600
skinparam maxMessageSize        150
skinparam StereotypeAlignment   right

skinparam title {
  FontSize  $TITLE_FONTSIZE
}

<style>
    Arrow {
        LineColor $RELATIONSHIP_LINECOLOR
        FontColor $RELATIONSHIP_FONTCOLOR
        FontSize $RELATIONSHIP_FONTSIZE
    }
    folder {
        .group {
            BackgroundColor $GROUP_FILLCOLOR
            Shadowing 2
            stereotype {
                FontSize 1
                FontColor transparent
            }

        }
        .grouping {
            LineColor $FOLDER_LINECOLOR
            LineStyle 8-5
            Shadowing 2
            stereotype {
                FontSize 1
                FontColor transparent
            }
        }
    }
    rectangle {
        .boundary {
            LineColor $FOLDER_LINECOLOR
            LineStyle 8-5
            Shadowing 0
            stereotype {
                FontSize 1
                FontColor transparent
            }
        }
    }
</style>

skinparam archimate {
  RoundCorner<<strategy-capability>> 25
  RoundCorner<<strategy-course-of-action>> 25
  RoundCorner<<strategy-value-stream>> 25
  RoundCorner<<business-process>> 25
  RoundCorner<<business-event>> 25
  RoundCorner<<business-function>> 25
  RoundCorner<<business-interaction>> 25
  RoundCorner<<business-event>> 25
  RoundCorner<<business-service>> 25
  RoundCorner<<application-function>> 25
  RoundCorner<<application-interaction>> 25
  RoundCorner<<application-process>> 25
  RoundCorner<<application-event>> 25
  RoundCorner<<application-service>> 25
  RoundCorner<<technology-function>> 25
  RoundCorner<<technology-process>> 25
  RoundCorner<<technology-interaction>> 25
  RoundCorner<<technology-event>> 25
  RoundCorner<<technology-infra-service>> 25
  RoundCorner<<implementation-workpackage>> 25
  RoundCorner<<implementation-event>> 25
  DiagonalCorner<<motivation-stakeholder>> 12
  DiagonalCorner<<motivation-driver>> 12
  DiagonalCorner<<motivation-assessment>> 12
  DiagonalCorner<<motivation-goal>> 12
  DiagonalCorner<<motivation-outcome>> 12
  DiagonalCorner<<motivation-principle>> 12
  DiagonalCorner<<motivation-requirement>> 12
  DiagonalCorner<<motivation-constraint>> 12
}
skinparam usecase {
  BorderColor #000000
}